minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - '@tktb-tess/*'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@tktb-tess/my-zod-schema'
  - '@vercel/speed-insights'
  - esbuild

overrides:
  cookie@<0.7.0: '>=0.7.0'
