[package]
name = "wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
js-sys = "0.3.77"
serde = "1.0.219"
serde_json = "1.0.140"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = ["Window"] }