[package]
name = "wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
serde_json = "1.0"
anyhow = "1.0"
num-bigint = "0.4"
js-sys = "0.3"

[dependencies.serde]
version = "1.0"
features = ["derive"]